from pathlib import Path
import json
root=Path(__file__).resolve().parents[1]
lines=['#pragma once','// Generated by tools/embed_lottie.py; edit assets/lottie/*.json.','namespace ncir_lottie_assets {']
for name in ('cold','good','hot','fan','smoke_fan'):
    data=json.loads((root/'assets/lottie'/f'{name}.json').read_text())
    assert data['w'] > 0 and data['h'] > 0 and data['op'] > data['ip'] and data['fr'] > 0
    compact=json.dumps(data,separators=(',',':'))
    lines.append(f'inline constexpr char {name}[] = R"lottie({compact})lottie";')
lines.append('}')
(root/'include/ncir_lottie_assets.h').write_text('\n'.join(lines)+'\n')
print('Embedded five Lottie JSON assets.')
